export enum ScreenEnum {
    Login = 'Login',
    LocationAccess = 'LocationAccess',
    Home = 'Home',
    ScanQr = 'ScanQr',
    Promotion = 'Promotion',
    Unlock = 'Unlock',
    TripHistoryDetails = 'TripHistoryDetails',
    Notifications = 'Notifications',
    Invoices = 'Invoices',
    InvoicePdf = 'InvoicePdf',
    TripsRating = 'TripsRating',
    QrScanner = 'QrScanner',
    History = 'History',
    Bikes = 'Bikes',
    Scooters = 'Scooters',
    Payment = 'Payment',
    PayUnPaid = 'PayUnPaid',
    AddPaymentMethod = 'AddPaymentMethod',
    MainStack = 'MainStack',
    Auth = 'Auth',
    HomeStack = 'HomeStack',
    Loading = 'Loading',
    LanguageSelection = 'LanguageSelection',
    Onboarding = 'Onboarding',
    Main = 'Main',
    Settings = 'Settings',
    Wallet='Wallet'
    // Add more screens here as needed
}
